name: reviewdog

on: [push, pull_request]

jobs:
  build:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-v2-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-v2-

      - run: npm i -g pnpm
      - run: pnpm i --frozen-lockfile

      - uses: reviewdog/action-eslint@v1
        with:
          reporter: eslint-check
          eslint_flags: '--ext .js,.ts,.md,.vue ./'
